### ISSUE TITLE
JaCoCo beüzemelési hibák javítása

### ISSUE THREAD

**Issue by elodchertesraffai** [BME-MIT-IET/Integratorok-iet-2019#28]
JaCoCo riport készítése parancssorból a ./gradlew jacocoTestReport utasítás kiadásával.

**Elvárt működés**

Létrejön a jelentés

**Aktuális működés**

Most már megfelelően működig a JaCoCo.

Az előző Issue-ban hivatkozott változtatásoknak sajnos az lett az eredménye, hogy a projektet nem lehetett buildelni. A hibákat kijavítottam, most már megfelelő a működés, a kódlefedettséget tartalmazó jelentések elkészülnek.

**Comment by elodchertesraffai** [comment]
Pull-request: #27

**Comment by elodchertesraffai** [comment]
Commit: b137a66 és 278e1e6

**Comment by sztomi97** [comment]
Jacoco report készítés működik.
